### ISSUE TITLE
Support for HEC-RAS 6.4.1

### ISSUE THREAD

**Issue by Freestyleyang** [quantum-dan/raspy-cal#23]
Hi There,

Thank you for developing such a great Python package for HEC-RAS calibration. Is it possible to add support with HEC-RAS 6.4.1? Thank you.

Regards,
Yang

**Comment by quantum-dan** [comment]
Should be a straightforward change, since Raspy now has support for HEC-RAS 6.  I will look into updating it next week.

**Comment by Freestyleyang** [comment]
Wonderful! Thank you for your continuous work on this great package. I look forward to trying the updated package. Have a good one.

**Comment by quantum-dan** [comment]
Just slightly late, but there is now an option to specify HEC-RAS version.  I've done some light testing, but not extensive.
